#pragma once

#include <WwiseProjectDatabase/AdapterTypes/Standard/WwiseStandardTypes.h>
#include <WwiseProjectDatabase/AdapterTypes/WwiseWrapperTypes.h>
#include <WwiseProjectDatabase/Ref/WwiseRefForwardDeclarations.h>
#include <WwiseProjectDatabase.cpp>
#include <WwiseProjectDatabase/AdapterTypes/Standard/WwiseProjectDatabaseLoggingUtils.cpp>
#include <WwiseProjectDatabase/AdapterTypes/Standard/WwiseProjectDatabaseStandardLogging.cpp>
#include <WwiseProjectDatabase/Metadata/WwiseMetadataAcousticTexture.cpp>
#include <WwiseProjectDatabase/Metadata/WwiseMetadataActionEntries.cpp>
#include <WwiseProjectDatabase/Metadata/WwiseMetadataBasicReference.cpp>
#include <WwiseProjectDatabase/Metadata/WwiseMetadataBus.cpp>
#include <WwiseProjectDatabase/Metadata/WwiseMetadataDialogue.cpp>
#include <WwiseProjectDatabase/Metadata/WwiseMetadataEvent.cpp>
#include <WwiseProjectDatabase/Metadata/WwiseMetadataExternalSource.cpp>
#include <WwiseProjectDatabase/Metadata/WwiseMetadataGameParameter.cpp>
#include <WwiseProjectDatabase/Metadata/WwiseMetadataGroupValueReference.cpp>
#include <WwiseProjectDatabase/Metadata/WwiseMetadataLanguage.cpp>
#include <WwiseProjectDatabase/Metadata/WwiseMetadataLoadable.cpp>
#include <WwiseProjectDatabase/Metadata/WwiseMetadataLoader.cpp>
#include <WwiseProjectDatabase/Metadata/WwiseMetadataMedia.cpp>
#include <WwiseProjectDatabase/Metadata/WwiseMetadataPlatform.cpp>
#include <WwiseProjectDatabase/Metadata/WwiseMetadataPlatformInfo.cpp>
#include <WwiseProjectDatabase/Metadata/WwiseMetadataPlugin.cpp>
#include <WwiseProjectDatabase/Metadata/WwiseMetadataPluginGroup.cpp>
#include <WwiseProjectDatabase/Metadata/WwiseMetadataPluginInfo.cpp>
#include <WwiseProjectDatabase/Metadata/WwiseMetadataPluginLib.cpp>
#include <WwiseProjectDatabase/Metadata/WwiseMetadataProject.cpp>
#include <WwiseProjectDatabase/Metadata/WwiseMetadataProjectInfo.cpp>
#include <WwiseProjectDatabase/Metadata/WwiseMetadataRootFile.cpp>
#include <WwiseProjectDatabase/Metadata/WwiseMetadataRootPaths.cpp>
#include <WwiseProjectDatabase/Metadata/WwiseMetadataSettings.cpp>
#include <WwiseProjectDatabase/Metadata/WwiseMetadataSoundBank.cpp>
#include <WwiseProjectDatabase/Metadata/WwiseMetadataSoundBanksInfo.cpp>
#include <WwiseProjectDatabase/Metadata/WwiseMetadataState.cpp>
#include <WwiseProjectDatabase/Metadata/WwiseMetadataStateGroup.cpp>
#include <WwiseProjectDatabase/Metadata/WwiseMetadataSwitch.cpp>
#include <WwiseProjectDatabase/Metadata/WwiseMetadataSwitchContainer.cpp>
#include <WwiseProjectDatabase/Metadata/WwiseMetadataSwitchGroup.cpp>
#include <WwiseProjectDatabase/Metadata/WwiseMetadataSwitchValue.cpp>
#include <WwiseProjectDatabase/Metadata/WwiseMetadataTrigger.cpp>
#include <WwiseProjectDatabase/Ref/WwiseAnyRef.cpp>
#include <WwiseProjectDatabase/Ref/WwiseRefAcousticTexture.cpp>
#include <WwiseProjectDatabase/Ref/WwiseRefAudioDevice.cpp>
#include <WwiseProjectDatabase/Ref/WwiseRefAuxBus.cpp>
#include <WwiseProjectDatabase/Ref/WwiseRefBus.cpp>
#include <WwiseProjectDatabase/Ref/WwiseRefCustomPlugin.cpp>
#include <WwiseProjectDatabase/Ref/WwiseRefDialogueArgument.cpp>
#include <WwiseProjectDatabase/Ref/WwiseRefDialogueEvent.cpp>
#include <WwiseProjectDatabase/Ref/WwiseRefEvent.cpp>
#include <WwiseProjectDatabase/Ref/WwiseRefExternalSource.cpp>
#include <WwiseProjectDatabase/Ref/WwiseRefGameParameter.cpp>
#include <WwiseProjectDatabase/Ref/WwiseRefLanguage.cpp>
#include <WwiseProjectDatabase/Ref/WwiseRefMedia.cpp>
#include <WwiseProjectDatabase/Ref/WwiseRefPlatform.cpp>
#include <WwiseProjectDatabase/Ref/WwiseRefPlatformInfo.cpp>
#include <WwiseProjectDatabase/Ref/WwiseRefPluginInfo.cpp>
#include <WwiseProjectDatabase/Ref/WwiseRefPluginLib.cpp>
#include <WwiseProjectDatabase/Ref/WwiseRefPluginShareSet.cpp>
#include <WwiseProjectDatabase/Ref/WwiseRefProjectInfo.cpp>
#include <WwiseProjectDatabase/Ref/WwiseRefRootFile.cpp>
#include <WwiseProjectDatabase/Ref/WwiseRefSoundBank.cpp>
#include <WwiseProjectDatabase/Ref/WwiseRefSoundBanksInfo.cpp>
#include <WwiseProjectDatabase/Ref/WwiseRefState.cpp>
#include <WwiseProjectDatabase/Ref/WwiseRefStateGroup.cpp>
#include <WwiseProjectDatabase/Ref/WwiseRefSwitch.cpp>
#include <WwiseProjectDatabase/Ref/WwiseRefSwitchContainer.cpp>
#include <WwiseProjectDatabase/Ref/WwiseRefSwitchGroup.cpp>
#include <WwiseProjectDatabase/Ref/WwiseRefTrigger.cpp>
#include <WwiseProjectDatabase/WwiseDataStructure.cpp>
#include <WwiseProjectDatabase/WwiseDatabaseIdentifiers.cpp>
#include <WwiseProjectDatabase/WwiseDirectoryVisitor.cpp>
#include <WwiseProjectDatabase/WwiseGeneratedFiles.cpp>