#include "ak_utils.h"

using namespace godot;

void AkUtils::_bind_methods()
{
	BIND_ENUM_CONSTANT(GAMEEVENT_NONE);
	BIND_ENUM_CONSTANT(GAMEEVENT_ENTER_TREE);
	BIND_ENUM_CONSTANT(GAMEEVENT_READY);
	BIND_ENUM_CONSTANT(GAMEEVENT_EXIT_TREE);

	BIND_ENUM_CONSTANT(AKTYPE_EVENT);
	BIND_ENUM_CONSTANT(AKTYPE_BANK);
	BIND_ENUM_CONSTANT(AKTYPE_RTPC);
	BIND_ENUM_CONSTANT(AKTYPE_STATE_GROUP);
	BIND_ENUM_CONSTANT(AKTYPE_STATE);
	BIND_ENUM_CONSTANT(AKTYPE_SWITCH_GROUP);
	BIND_ENUM_CONSTANT(AKTYPE_SWITCH);
	BIND_ENUM_CONSTANT(AKTYPE_BUS);
	BIND_ENUM_CONSTANT(AKTYPE_AUX_BUS);
}
